E-DIARY-main/testapp/app1/urls.py
from django.urls import path
from . import views

app_name = 'app1'
urlpatterns = [
    path('', views.main, name='main'),
    path('grade', views.student, name='grade'),
    path('form', views.authorization, name='form'),
    path('homework', views.homework, name='homework'),
    path('timetable', views.timetable, name='timetable'),
    path('progress_table', views.progress_table, name='progress_table'),
    path('quit', views.quit, name='quit')
]

E-DIARY-main/testapp/testapp/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path

urlpatterns = [
    path('', include('app1.urls')),
    path('admin/', admin.site.urls),
    # path('account/', include('account.urls')),
]

E-DIARY-main/testapp/app1/models.py
from django.db import models
from datetime import date


class Classes(models.Model):
    number = models.CharField(max_length=7)

    def __str__(self):
        return self.number

    class Meta:
        verbose_name = 'Класс'
        verbose_name_plural = 'Классы'


class Users(models.Model):
    login = models.CharField('Логин', unique=True, max_length=200)
    password = models.CharField('Пароль', max_length=200)
    name = models.CharField('ФИО', max_length=200)
    is_active = models.BooleanField('Работает/Учится', default=True)

    def __str__(self):
        return self.login

    class Meta:
        abstract = True


class Students(Users):
    user_class = models.ForeignKey(Classes, on_delete=models.PROTECT)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Ученик'
        verbose_name_plural = 'Ученики'


class Teachers(Users):
    pass

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Преподаватель'
        verbose_name_plural = 'Преподаватели'


class Lessons(models.Model):
    name = models.CharField(max_length=200, unique=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Предмет'
        verbose_name_plural = 'Предметы'


class GradeType(models.IntegerChoices):
    lesson_work = 1, 'Работа на уроке'
    test = 2, 'Самостоятельная работа'
    control_test = 3, 'Контрольная работа'
    homework = 4, 'Домашняя работа'


class LessonStatus(models.IntegerChoices):
    active = 1, 'Активный'
    canceled = 2, 'Отменен'
    switched = 3, 'Замена'


class GradeList(models.IntegerChoices):
    one = 1, '1'
    two = 2, '2'
    three = 3, '3'
    four = 4, '4'
    five = 5, '5'


class TimeSlot(models.Model):
    time_begin = models.TimeField(unique=True)
    time_end = models.TimeField(unique=True)

    def __str__(self):
        return self.time_begin.isoformat(timespec='minutes') + "-" + self.time_end.isoformat(timespec='minutes')

    class Meta:
        verbose_name = 'Время урока'
        verbose_name_plural = 'Время уроков'


class OneLesson(models.Model):
    date = models.DateField()
    lesson_time = models.ForeignKey(TimeSlot, on_delete=models.PROTECT)
    lesson = models.ForeignKey(Lessons, on_delete=models.PROTECT)
    homework = models.CharField(max_length=500, blank=True)
    teacher = models.ForeignKey(Teachers, on_delete=models.PROTECT)
    a_class = models.ForeignKey(Classes, on_delete=models.PROTECT)
    lesson_status = models.IntegerField(choices=LessonStatus.choices, default=1)
    comment_teacher = models.CharField(max_length=500, blank=True)

    def __str__(self):
        return self.lesson.name

    class Meta:
        verbose_name = 'Расписание урока'
        verbose_name_plural = 'Расписание уроков'
        constraints = [
            models.UniqueConstraint(fields=['date', 'lesson_time', 'a_class'], name='unique_lesson')
        ]


def norm_view_for(grade_type):
    if grade_type == 1:
        return 'Работа на уроке'
    elif grade_type == 2:
        return 'Самостоятельная работа'
    elif grade_type == 3:
        return 'Контрольная работа'
    elif grade_type == 4:
        return 'Домашняя работа'
    else:
        return ' Ошибка '


class Grade(models.Model):
    # оценка
    student = models.ForeignKey(Students, on_delete=models.PROTECT)
    lesson = models.ForeignKey(OneLesson, on_delete=models.PROTECT)
    grade = models.IntegerField(choices=GradeList.choices)
    grade_type = models.IntegerField(choices=GradeType.choices)
    # дата за которую ставится оценка
    grade_date = models.DateField(default=date.today)

    def __str__(self):
        return str(self.student) + ' Оценка: ' + str(self.grade) + ' ' + norm_view_for(self.grade_type) + ' ' + str(
            self.lesson) + ' ' + str(self.grade_date)

    class Meta:
        verbose_name = 'Оценка'
        verbose_name_plural = 'Оценки'


class LogUser(models.Model):
    key = models.ForeignKey(Students, on_delete=models.PROTECT)

E-DIARY-main/testapp/app1/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.db import models
import datetime
from app1.models import *
from django.core.exceptions import ObjectDoesNotExist
from app1.utils import get_timetable, get_timetable_week, get_date_to_string


def main(request):
    if len(LogUser.objects.all()) == 0:
        return redirect('/form')
    url_name = request.resolver_match.url_name
    user = LogUser.objects.all()[0].key
    user_name = user.name
    user_class = user.user_class
    date = datetime.date.today()
    return render(request, 'app1/main.html', {'url_name': url_name, 'class': user_class, 'name': user_name,
                                              'timetable': get_timetable(date, user_class)})


def homework(request):
    if len(LogUser.objects.all()) == 0:
        return redirect('/form')
    url_name = request.resolver_match.url_name
    user = LogUser.objects.all()[0].key
    user_name = user.name
    user_class = user.user_class
    date = datetime.date.today()
    if request.GET.get('date') is not None:
        date = datetime.datetime.strptime(request.GET.get('date'), '%Y-%m-%d')
    return render(request, 'app1/homework.html', {'url_name': url_name, 'class': user_class, 'name': user_name,
                                                  'timetable': get_timetable(date, user_class),
                                                  'date': get_date_to_string(date)})


def timetable(request):
    if len(LogUser.objects.all()) == 0:
        return redirect('/form')
    url_name = request.resolver_match.url_name
    user = LogUser.objects.all()[0].key
    user_name = user.name
    user_class = user.user_class
    date = datetime.date.today()
    return render(request, 'app1/timetable.html', {'url_name': url_name, 'class': user_class, 'name': user_name,
                                                   'timetable': get_timetable_week(date, user_class)})


def progress_table(request):
    if len(LogUser.objects.all()) == 0:
        return redirect('/form')
    url_name = request.resolver_match.url_name
    user = LogUser.objects.all()[0].key
    user_name = user.name
    user_class = user.user_class
    return render(request, 'app1/progress_table.html', {'url_name': url_name, 'class': user_class, 'name': user_name})


def student(request):
    if len(LogUser.objects.all()) == 0:
        return redirect('/form')
    url_name = request.resolver_match.url_name
    name = Lessons.objects.all()
    grade = Grade.objects.all()
    user = LogUser.objects.all()[0].key
    user_name = user.name
    user_class = user.user_class
    return render(request, 'app1/grade.html', {'url_name': url_name, 'class': user_class, 'name': user_name})


def authorization(request):
    if request.method == 'POST':
        login = request.POST.get('login')
        password = request.POST.get('password')
        try:
            user = Students.objects.get(login=login, password=password)
            if len(LogUser.objects.filter(key=user)) > 0:
                key = LogUser.objects.all()[0]
                key.delete()
                key = LogUser(key=user)
                key.save()
                return redirect('/')
            else:
                key = LogUser(key=user)
                key.save()
                return redirect('/')
        except ObjectDoesNotExist:
            return HttpResponse(status=400)
    else:
        return render(request, 'app1/form.html')


def quit(request):
    user = LogUser.objects.all()[0]
    user.delete()
    return render(request, 'app1/form.html')

E-DIARY-main/testapp/app1/templates/app1/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
  <title>E-DIARY</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" type="text/javascript"></script>
  <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous">
    </script>
  <link href="{% static 'css/app1.css' %}" rel="stylesheet" type="text/css"/>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">E-DIARY</a>
      <ul class="navbar-nav">
        <li class="nav-item {% if url_name == 'main' %}active{% endif %}">
          <a class="nav-link" href="{% url 'app1:main'%}">Главная</a>
        </li>
        <li class="nav-item {% if url_name == 'timetable' %}active{% endif %}">
          <a class="nav-link" href="{% url 'app1:timetable'%}">Расписание</a>
        </li>
        <li class="nav-item {% if url_name == 'homework' %}active{% endif %}">
          <a class="nav-link" href="{% url 'app1:homework'%}">Домашнее задание</a>
        </li>
        <li class="nav-item {% if url_name == 'grade' %}active{% endif %}">
          <a class="nav-link " href="{% url 'app1:grade'%}">Оценки</a></a>
        </li>
        <li class="nav-item {% if url_name == 'progress_table' %}active{% endif %}">
          <a class="nav-link " href="{% url 'app1:progress_table'%}">Успеваемость</a></a>
        </li>
        <li class="nav-item {% if url_name == 'form' %}active{% endif %}">
          <a class="nav-link " href="{% url 'app1:quit'%}">Выход</a>
        </li>
      </ul>
</nav>

<div class="jumbotron text-center" >
  <div class="row">
  <div class="col-sm-3"><h5>Класс: {{class}}</h5></div>
    <div class="col-sm"><h5>{{name}}</h5></div>
</div>
</div>
<div class=".container-fluid">
{% block content %}
{% endblock %}
</div>
<script type="text/javascript">

    /* функция добавления ведущих нулей */
    /* (если число меньше десяти, перед числом добавляем ноль) */
    function zero_first_format(value)
    {
        if (value < 10)
        {
            value='0'+value;
        }
        return value;
    }

    /* функция получения текущей даты и времени */
    function date_time()
    {
        var current_datetime = new Date();
        var day = zero_first_format(current_datetime.getDate());
        var month = zero_first_format(current_datetime.getMonth()+1);
        var year = current_datetime.getFullYear();
        var hours = zero_first_format(current_datetime.getHours());
        var minutes = zero_first_format(current_datetime.getMinutes());
        var seconds = zero_first_format(current_datetime.getSeconds());
        let dayOfTheWeek = ['Воскресенье','Понедельник','Вторник','Среда','Четверг','Пятница','Суббота']

        return day+"."+month+"."+year+" "+ dayOfTheWeek[current_datetime.getUTCDay()]+" "+hours+":"+minutes;
    }

    /* update date every second */
    setInterval(() => document.getElementById('current_date_time_block').innerHTML = date_time(),1000)

</script>
</body>
</html>

E-DIARY-main/testapp/app1/templates/app1/form.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
  <title>E-DIARY</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" type="text/javascript"></script>
  <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous">
    </script>
  <link href="{% static 'css/app1.css' %}" rel="stylesheet" type="text/css"/>
</head>

<body>
<div class="container">
  <h2 class="text-center">Вход</h2>
  <form method="POST" action="{% url 'app1:form' %}">
    {% csrf_token %}
    <div class="form-group">
      <label class="control-label col-sm-2" for="login">Login:</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="login" placeholder="Enter login" name="login">
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-2" for="pwd">Пароль:</label>
      <div class="col-sm-10">
        <input type="password" class="form-control" id="pwd" placeholder="Enter password" name="password">
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <input type="submit" value="Вход" class="btn btn-light"/>
      </div>
    </div>
  </form>
</div>

</body>
</html>

E-DIARY-main/testapp/app1/templates/app1/grade.html
{% extends 'app1/base.html' %}

{% block title %}Оценки{% endblock %}

{% block content %}

<h4>Оценки</h4>
<table class="table table-bordered">
{% for el in name %}
{% for ele in grade %}
    <div class=" name-output">
        <tbody>
        <tr>
        <td>{{el.name}}</td>
        <td>{{el.user_class}}</td>
            <td>{{ele.grade}}</td>
        </tr>
        </tbody>
    </div>
{%endfor%}
{%endfor%}
{% endblock %}

E-DIARY-main/testapp/app1/templates/app1/homework.html
{% extends 'app1/base.html' %}
{% load static %}
{% block title %}Домашнее задание{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
      <div class="col-2"><button type="button" class="btn btn-outline-dark" onclick="rewindDate('prev')"><<</button></div>
      <div class="col text-center"><h4>Расписание на {{date}}</h4></div>
      <div class="col-2"><button type="button" class="btn btn-outline-dark float-right" onclick="rewindDate('next')">>></button></div>
  </div>
  <table class="table table-bordered table-striped mt-3">
      <tr><th>№</th><th>Время</th><th>Урок</th><th>Домашнее задание</th><th>Комментарий преподавателя</th></tr>
      {% for lesson in timetable %}
      <div class=" name-output">
      <tr>
        <td>{{lesson.number}}</td><td>{{lesson.time}}</td><td>{{lesson.title}}</td><td>{{lesson.homework}}</td><td>{{lesson.comment}}</td>
      </tr>
      </div>
      {% endfor %}
  </table>
</div>
<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
{% endblock %}

E-DIARY-main/testapp/app1/templates/app1/main.html
{% extends 'app1/base.html' %}

{% block title %}Главная страница{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col"><h4>Расписание на сегодня.</h4></div>
    <div class="font-size-lg col" id="current_date_time_block"></div>
  </div>
  <table class="table table-bordered table-striped">
      <tr><th>№</th><th>Время</th><th>Урок</th><th>Домашнее задание</th></tr>
      {% for lesson in timetable %}
      <div class=" name-output">
      <tr>
        <td>{{lesson.number}}</td><td>{{lesson.time}}</td><td>{{lesson.title}}</td><td>{{lesson.homework}}</td>
      </tr>
      </div>
      {% endfor %}
  </table>
</div>
{% endblock %}

E-DIARY-main/testapp/app1/templates/app1/progress_graph.html
{% extends 'app1/base.html' %}

{% block title %}Успеваемость график{% endblock %}

{% block content %}
<h4>Успеваемость график </h4>

{% endblock %}

E-DIARY-main/testapp/app1/templates/app1/progress_table.html
{% extends 'app1/base.html' %}

{% block title %}Успеваемость таблица{% endblock %}

{% block content %}

<h4>Таблица успеваемости</h4>

{% endblock %}

E-DIARY-main/testapp/app1/templates/app1/timetable.html
{% extends 'app1/base.html' %}

{% block title %}Расписание{% endblock %}

{% block content %}
<div class="container">
  {% for day in timetable%}
  <div class="row">
    <div class="col text-center"><h4>Расписание на {{day.date}}</h4></div>
  </div>
  <table class="table table-bordered table-striped mt-3">
      <tr><th>№</th><th>Время</th><th>Урок</th><th>Домашнее задание</th></tr>
      {% for lesson in day.lessons %}
      <div class=" name-output">
      <tr>
        <td>{{lesson.number}}</td><td>{{lesson.time}}</td><td>{{lesson.title}}</td><td>{{lesson.homework}}</td>
      </tr>
      </div>
      {% endfor %}
  </table>
    {% endfor %}
</div>
{% endblock %}